# Generated by Django 3.0.6 on 2020-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=10, unique=True)),
                ('faculty_name', models.CharField(max_length=20)),
                ('starting_date', models.DateField()),
                ('course_time', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=20)),
                ('Contact_Number', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Student_Course', models.ManyToManyField(to='app1.courseModel')),
            ],
        ),
    ]
