# Generated by Django 3.0.6 on 2020-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stud_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Student_Course',
        ),
    ]
